# Generated by Django 4.0 on 2023-03-30 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping_cart',
            name='client',
        ),
    ]
