# Generated by Django 4.0 on 2023-03-28 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='is_avalable',
            new_name='is_available',
        ),
    ]
