# Generated by Django 4.0 on 2023-04-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_remove_shopping_cart_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='resume',
            field=models.CharField(default=None, max_length=350),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(max_length=750),
        ),
    ]
