# Generated by Django 4.0 on 2023-03-29 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_rename_is_avalable_products_is_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_category',
            new_name='product_subcategory',
        ),
    ]
