# Generated by Django 4.0 on 2023-04-27 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_products_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_cart',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_client', to='register.clients'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
